stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: maven:3.9.5-eclipse-temurin-21
  script:
    - echo "Navigating to backend folder..."
    - cd ./demo
    - echo "Compiling the backend code..."
    - mvn clean compile
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: maven:3.9.5-eclipse-temurin-21
  variables:
    SPRING_PROFILES_ACTIVE: "test"
  script:
    - echo "Navigating to backend folder..."
    - cd ./demo
    - echo "Running tests with Spring profile test"
    - mvn test
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - demo/target/surefire-reports/
    reports:
      junit: demo/target/surefire-reports/*.xml

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
