services:
  frontend:
    image: "my-react-app:latest"
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: "demo:latest"
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: P14MySQL
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: splunge
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db:
      
